# Generated by Django 4.2.6 on 2023-10-17 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='エリア名')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='カテゴリー名')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='セミナー名')),
                ('host', models.CharField(max_length=100, verbose_name='主催者')),
                ('description', models.TextField(verbose_name='セミナー詳細')),
                ('image', models.ImageField(blank=True, default='images/noimage.png', upload_to='images/', verbose_name='画像')),
                ('fee', models.IntegerField(verbose_name='参加費')),
                ('capacity', models.IntegerField(verbose_name='定員')),
                ('venue', models.CharField(max_length=250, verbose_name='会場')),
                ('date', models.DateField(verbose_name='日付')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seminar2.area', verbose_name='エリア')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seminar2.category', verbose_name='カテゴリー')),
            ],
        ),
    ]
