# Generated by Django 4.2.8 on 2023-12-16 08:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0002_transcription_delete_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='audio_file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='media/'),
            preserve_default=False,
        ),
    ]
