# Generated by Django 4.2.8 on 2023-12-18 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0003_translation_audio_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transcription',
        ),
    ]
